describe('The ultimate e2e run', () => {
  it('Hopefully everthing works as expected :)', () => {
    cy.visit('/')
    const searchInput = cy.get('input[placeholder="Search devices by name or abbreviation"]')
    searchInput.type('nano')
    const searchResults = searchInput.siblings('div')
    searchResults.within(() => {
      cy.get('a').contains('Station loco M5').trigger('mouseover')
    })
    const deviceCard = searchResults.siblings('div')
    deviceCard.within(() => {
      cy.get('span').contains('NanoStation loco M5')
      cy.get('span').contains('LM5, LocoM5')
      cy.get('span').contains('airMAX')
      cy.get('img[src="https://static.ui.com/fingerprint/ui/icons/07289d4a-167b-464d-827d-a215aae6ba0d_128x128.png"]').should('exist')
    })
    searchResults.within(() => { cy.get('a').contains('Station loco M5').click() })
    cy.url().should('include', '/devices/aa529bfc-4217-4942-96f8-1742b8ab8764')
    cy.get('img[src="https://static.ui.com/fingerprint/ui/images/aa529bfc-4217-4942-96f8-1742b8ab8764/default/adbf171af99586757312154296ba110d.png"]').should('exist')
    cy.get('h1').contains('NanoStation loco M5')
    cy.get('button').contains('See All Details as JSON').click()
    cy.contains('h2', 'NanoStation loco M5').should('exist')
    cy.get('div').contains('"id":"07289d4a-167b-464d-827d-a215aae6ba0d"').should('exist')
    cy.get('button').contains('Make it pretty!').click()
    cy.get('button').contains('Make it pretty!').should('not.exist')
    cy.get('button').contains('I prefer raw :)').click()
    cy.get('button').contains('Make it pretty!').should('exist')
    cy.get('button').contains('Copy JSON').should('exist')
    cy.get('button[role="close-button"]').click()
    cy.contains('h2', 'NanoStation loco M5').should('not.exist')
    cy.get('button[role="previous-button"]').click()
    cy.url().should('include', '/devices/0a34d79d-c382-4d5b-9b9b-8da38bdbd35c')
    cy.contains('h1', 'NanoStation loco M2').should('exist')
    cy.get('button[role="next-button"]').click().click()
    cy.url().should('include', '/devices/693fcee9-13cc-438b-93bc-83de96848ad5')
    cy.contains('h1', 'mPort').should('exist')
    cy.get('a').contains('Back').click()
    cy.url().should('eq', Cypress.config().baseUrl + '/')
    cy.get('input[placeholder="Search devices by name or abbreviation"]').should('exist')
    cy.get('a').contains('airFiber X 2G24-S45 Antenna').click()
    cy.url().should('include', '/devices/af542e33-bf95-47fb-b891-a368ccb7fa40')
    cy.get('a[role="logo"]').click()
    cy.url().should('eq', Cypress.config().baseUrl + '/')
    cy.get('button[role="grid-view-toggle"]').click()
    cy.get('div[role="grid-view"]').should('exist')
    cy.get('div[role="device-card"]')
      .should('have.length', 507)
      .contains('AF-11G35, AirFiber X 11G35 Antenna')
      .should('exist')
    cy.get('button').contains('Filter').click()
    cy.get('div[role="filter-options"]').should('exist')
    cy.get('button').contains('Reset').should('be.disabled')
    cy.get('label').contains('UniFi LTE').click()
    cy.get('div[role="device-card"]').should('have.length', 3)
    cy.get('label').contains('UniFi Access').click()
    cy.get('div[role="device-card"]').should('have.length', 19)
    cy.get('button').contains('Reset').should('be.enabled').click()
    cy.get('div[role="device-card"]').should('have.length', 507)
    cy.get('button[role="list-view-toggle"]').click()
    cy.get('div[role="filter-options"]').should('not.exist')
    cy.get('div[role="list-view"]').should('exist')
  })
})